name: build-test

on:
  pull_request:
    branches:
    - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Build style spec
      run: |
        npm run generate-style-spec
        npm run generate-typings
        npm run build
        npm run compile

    - name: Build docs
      run: |
        cd ./docs
        npm ci
        npm run build
        npm run test
